### ISSUE TITLE
Do not leave spaces open when naming pictures

### ISSUE THREAD

**Issue by buronbekdev** [Otabekov12/trafalgar#1]
https://github.com/Otabekov12/trafalgar/blob/e0f94a13627dc9f58f9c09e499e7ac242dd5ac38/index.html#L69

**Comment by buronbekdev** [comment]
Rasmilar orasini probil qolib kettibdi valedatr hato beradi

**Comment by Otabekov12** [comment]
the reason for this error is that I did not check in the validator thank you
